# Generated by Django 5.1.4 on 2024-12-18 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Nomi')),
                ('definition', models.TextField(blank=True, null=True, verbose_name='Tavsiri')),
            ],
            options={
                'verbose_name': 'Turi',
                'verbose_name_plural': 'Turlari',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Flowers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nomi')),
                ('description', models.TextField(default="Avtor ma'lumot qo'shmadi:)", verbose_name='Tavsifi')),
                ('price', models.IntegerField(verbose_name='Narxi')),
                ('quantity', models.IntegerField(verbose_name='Soni')),
                ('published', models.BooleanField(default=False, help_text='Agar bu yerda - "False" bolsa bu gul sotuvda korinmaydi, Agar "True" bolsa korinadi', verbose_name='Korinadimi')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flowers.categories', verbose_name='Turi')),
            ],
            options={
                'verbose_name': 'Gul',
                'verbose_name_plural': 'Gullar',
                'ordering': ['-id'],
            },
        ),
    ]
